security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /
                enable_csrf: true
            logout:
                path: app_logout
                target: /

    access_control:
        # Autoriser l'accès à la page de connexion et ressources publiques
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js|images)/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Restreindre l'accès aux utilisateurs authentifiés pour le reste des pages
        - { path: ^/, roles: ROLE_USER }
